import { Comfortaa } from "next/font/google";
import { ConfigProvider } from "antd";
import "./globals.css";

const comfortaa = Comfortaa({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ConfigProvider
    theme={{
      token: {
        fontFamily: comfortaa.style.fontFamily
      }
    }}
    >
      <html lang="en">
        <body className={comfortaa.className}>{children}</body>
      </html>
    </ConfigProvider>

  );
}
